export const skillsData = [
    { id: 1, category: 'Cloud Technologies', name: 'AWS (EC2, Elastic Beanstalk, VPC, S3, IAM, CloudFront, CloudFormation, Lambda, SNS, Secrets Manager, API Gateway)' },
    { id: 2, category: 'Cloud Technologies', name: 'Azure (Active Directory, Virtual Machines, Storage, DevOps)' },
    { id: 3, category: 'Languages', name: 'C' },
    { id: 4, category: 'Languages', name: 'C++' },
    { id: 5, category: 'Languages', name: 'Java' },
    { id: 6, category: 'Languages', name: 'Python' },
    { id: 7, category: 'Languages', name: 'R' },
    { id: 8, category: 'Databases', name: 'SQL' },
    { id: 9, category: 'Databases', name: 'MySQL' },
    { id: 10, category: 'Databases', name: 'AWS RDS' },
    { id: 11, category: 'Databases', name: 'AWS DynamoDB' },
    { id: 12, category: 'Developer Technologies', name: 'HTML' },
    { id: 13, category: 'Developer Technologies', name: 'CSS' },
    { id: 14, category: 'Developer Technologies', name: 'React JS' },
    { id: 15, category: 'Developer Technologies', name: 'JavaScript' },
    { id: 16, category: 'Developer Technologies', name: 'Node JS' },
    { id: 17, category: 'Developer Technologies', name: 'Spring Boot' },
    { id: 18, category: 'Developer Technologies', name: 'React Native' },
    { id: 19, category: 'Developer Technologies', name: 'Vue JS' },
    { id: 20, category: 'Developer Technologies', name: 'Selenium' },
    { id: 21, category: 'Developer Technologies', name: 'Linux' },
    { id: 22, category: 'Developer Technologies', name: 'Postman' },
    { id: 23, category: 'Developer Technologies', name: 'Figma' },
    { id: 24, category: 'Developer Technologies', name: 'Insomnia' },
    { id: 25, category: 'DevOps Tools', name: 'Jenkins' },
    { id: 26, category: 'DevOps Tools', name: 'Docker' },
    { id: 27, category: 'DevOps Tools', name: 'CI/CD pipeline' },
    { id: 28, category: 'DevOps Tools', name: 'Jira' },
    { id: 29, category: 'DevOps Tools', name: 'Bamboo' },
    { id: 30, category: 'DevOps Tools', name: 'Bitbucket' },
    { id: 31, category: 'DevOps Tools', name: 'Git/GitHub' }
  ];